### ISSUE TITLE
pictures

### ISSUE THREAD

**Issue by melodykunyin** [JazzikPeng/Autonomous-Robot-Car#1]
![IMG_2973](https://user-images.githubusercontent.com/38568141/75410569-f89ac580-58e1-11ea-9418-5e8baf42a9ef.jpg)
![IMG_2506](https://user-images.githubusercontent.com/38568141/75410587-05b7b480-58e2-11ea-96e9-1c325ac251fa.JPG)
![IMG_2972](https://user-images.githubusercontent.com/38568141/75410596-0b14ff00-58e2-11ea-8dfb-9550fcb33633.JPG)
![IMG_2974](https://user-images.githubusercontent.com/38568141/75410597-0c462c00-58e2-11ea-8228-de18ee9fe297.jpg)
![IMG_3127](https://user-images.githubusercontent.com/38568141/75410606-123c0d00-58e2-11ea-8427-6b3228760980.jpg)
![IMG_3130](https://user-images.githubusercontent.com/38568141/75410609-16682a80-58e2-11ea-8815-3ec3c3aaa3fe.jpg)

**Comment by JazzikPeng** [comment]
Awesome!
